[project]
name = "heard-from-vine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "feedparser>=6.0.11",
    "marimo>=0.11.13",
    "pandas>=2.2.3",
    "polars>=1.23.0",
]
